enableScripts: false
nodeLinker: node-modules
nmHoistingLimits: none
nmMode: hardlinks-local

supportedArchitectures:
    os:
        - darwin
        - linux
        - win32
    cpu:
        - x64
        - arm64
    libc:
        - glibc
        - musl