use bytemuck::{Pod, Zeroable};
use solana_account_info::AccountInfo;
use solana_program_error::ProgramError;
use solana_pubkey::Pubkey;

use crate::{
    constants::{case_status, seeds},
    error::ChanceryError,
};

// ─── Discriminator ────────────────────────────────────────────────────────────
pub const PROVENANCE_CASE_DISCRIMINATOR: [u8; 8] =
    [0x70, 0x72, 0x6f, 0x76, 0x63, 0x61, 0x73, 0x65];

// ─── Account size ─────────────────────────────────────────────────────────────
//   [u8;8]   discriminator             =  8 @ 0
//   u16      version                   =  2 @ 8
//   u8       bump                      =  1 @ 10
//   u8       status                    =  1 @ 11
//   [u8;4]   _pad0                     =  4 @ 12  -> [u8;32] at 16
//   [u8;32]  case_id                   = 32 @ 16
//   [u8;32]  counterparty              = 32 @ 48
//   [u8;32]  asset_mint                = 32 @ 80
//   [u8;32]  source_wallet             = 32 @ 112
//   [u8;32]  intake_compartment_id     = 32 @ 144
//   [u8;32]  target_compartment_id     = 32 @ 176
//   u32      reason_code               =  4 @ 208
//   [u8;4]   _pad1                     =  4 @ 212  -> [u8;32] at 216
//   [u8;32]  evidence_hash             = 32 @ 216
//   [u8;32]  opened_by                 = 32 @ 248
//   [u8;32]  approved_by               = 32 @ 280
//   [u8;32]  _reserved                 = 32 @ 312
//                                        ─────
//                                       344 bytes
pub const PROVENANCE_CASE_SIZE: usize = 344;

// ─── State ────────────────────────────────────────────────────────────────────

/// Provenance review case - used to document source-of-funds diligence,
/// sanitation decisions, and compartment promotion approvals.
///
/// Seed: [b"provenance-case", case_id]
///
/// Characterization (spec 06 §6.5):
///   - Not a customer-facing object.
///   - An internal Operator workflow record.
///   - Does not create any holder rights or entitlements.
///   - A closed ProvenanceCase may be referenced as evidence
///     when promoting a compartment balance.
#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable)]
pub struct ProvenanceCase {
    pub discriminator:         [u8; 8],
    pub version:               u16,
    pub bump:                  u8,
    
    /// One of `case_status::*` constants.
    pub status:                u8,
    pub _pad0:                 [u8; 4],

    /// Opaque case ID generated by the operator.
    pub case_id:               [u8; 32],
    
    /// The counterparty whose funds are under review.
    pub counterparty:          Pubkey,
    
    /// Collateral asset mint involved.
    pub asset_mint:            Pubkey,
    
    /// The on-chain wallet from which funds originated.
    pub source_wallet:         Pubkey,
    
    /// The compartment where funds currently sit pending review.
    pub intake_compartment_id: [u8; 32],
    
    /// The compartment funds should move to on approval.
    pub target_compartment_id: [u8; 32],

    /// Operator-defined reason / risk code for the case.
    pub reason_code:           u32,
    pub _pad1:                 [u8; 4],
    
    /// SHA-256 hash of the off-chain evidence bundle.
    pub evidence_hash:         [u8; 32],

    pub opened_by:             Pubkey,
    /// Zero until the case is approved.
    pub approved_by:           Pubkey,

    pub _reserved:             [u8; 32],
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
impl ProvenanceCase {
    pub fn pda(case_id: &[u8; 32], program_id: &Pubkey) -> (Pubkey, u8) {
        Pubkey::find_program_address(
            &[seeds::PROVENANCE_CASE, case_id.as_ref()],
            program_id,
        )
    }

    pub fn verify_pda(
        account:    &AccountInfo,
        case_id:    &[u8; 32],
        program_id: &Pubkey,
    ) -> Result<u8, ProgramError> {
        let (expected, bump) = Self::pda(case_id, program_id);

        if account.key != &expected {
            return Err(ChanceryError::InvalidPda.into());
        }

        Ok(bump)
    }

    pub fn load<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::Ref<'a, Self>, ProgramError> {
        let state = crate::state_loader::load_state::<Self>(
            account,
            PROVENANCE_CASE_SIZE,
            PROVENANCE_CASE_DISCRIMINATOR,
            ChanceryError::NotInitialized,
        )?;

        Ok(state)
    }

    /// Load initialized state and prove that its identity fields resolve to
    /// this account's canonical PDA and stored bump.
    pub fn load_verified<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::Ref<'a, Self>, ProgramError> {
        let state = Self::load(account)?;
        let expected_bump = Self::verify_pda(account, &state.case_id, &crate::id())?;

        if state.bump != expected_bump {
            return Err(ChanceryError::StoredBumpMismatch.into());
        }

        Ok(state)
    }

    pub fn load_mut<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::RefMut<'a, Self>, ProgramError> {
        let state = crate::state_loader::load_state_mut::<Self>(
            account,
            PROVENANCE_CASE_SIZE,
            PROVENANCE_CASE_DISCRIMINATOR,
            ChanceryError::NotInitialized,
        )?;

        Ok(state)
    }

    /// Mutable counterpart to `load_verified`.
    pub fn load_verified_mut<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::RefMut<'a, Self>, ProgramError> {
        let state = Self::load_mut(account)?;
        let expected_bump = Self::verify_pda(account, &state.case_id, &crate::id())?;

        if state.bump != expected_bump {
            return Err(ChanceryError::StoredBumpMismatch.into());
        }

        Ok(state)
    }

    pub fn load_uninitialized_mut<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::RefMut<'a, Self>, ProgramError> {
        crate::state_loader::load_uninitialized_state_mut::<Self>(
            account,
            PROVENANCE_CASE_SIZE,
            ChanceryError::AlreadyInitialized,
        )
    }

    // ── Guards ────────────────────────────────────────────────────────────────

    pub fn assert_open(&self) -> Result<(), ProgramError> {
        if self.status != case_status::OPEN {
            return Err(ChanceryError::ProvenanceCaseNotOpen.into());
        }

        Ok(())
    }

    pub fn assert_approved(&self) -> Result<(), ProgramError> {
        if self.status != case_status::APPROVED {
            return Err(ChanceryError::ProvenanceCaseNotOpen.into());
        }

        Ok(())
    }

    pub fn assert_not_already_approved(&self) -> Result<(), ProgramError> {
        if self.status == case_status::APPROVED {
            return Err(ChanceryError::ProvenanceCaseAlreadyApproved.into());
        }

        Ok(())
    }
}

// ─── Size assertion ───────────────────────────────────────────────────────────
const _: () = assert!(
    core::mem::size_of::<ProvenanceCase>() == PROVENANCE_CASE_SIZE,
    "ProvenanceCase size mismatch - update PROVENANCE_CASE_SIZE",
);
