use bytemuck::{Pod, Zeroable};
use solana_account_info::AccountInfo;
use solana_program_error::ProgramError;
use solana_pubkey::Pubkey;

use crate::{
    account_security::assert_optional_external_identity,
    constants::{pathway_kind, seeds, status_flag},
    error::ChanceryError,
};

// ─── Discriminator ────────────────────────────────────────────────────────────
pub const PATHWAY_POLICY_DISCRIMINATOR: [u8; 8] =
    [0x70, 0x77, 0x79, 0x70, 0x6f, 0x6c, 0x79, 0x00];

// ─── Account size ─────────────────────────────────────────────────────────────
//   [u8;8]   discriminator                         =  8 @ 0
//   u16      version                               =  2 @ 8
//   u8       bump                                  =  1 @ 10
//   u8       pathway_kind                          =  1 @ 11
//   [u8;4]   _pad0                                 =  4 @ 12
//   [u8;32]  pathway_id                            = 32 @ 16
//   [u8;32]  asset_mint                            = 32 @ 48
//   [u8;32]  issued_token_mint                     = 32 @ 80
//   [u64;2]  allowed_program_mask                  = 16 @ 112  (112%8=0 Y)
//   [u64;2]  allowed_instruction_mask              = 16 @ 128
//   [u8;32]  designated_executor                   = 32 @ 144
//   u64      source_account_policy                 =  8 @ 176  (176%8=0 Y)
//   u64      destination_account_policy            =  8 @ 184
//   [u8;32]  reserve_compartment_pol_id            = 32 @ 192
//   [u8;32]  limit_policy_id                       = 32 @ 224
//   [u8;32]  evidence_policy_id                    = 32 @ 256
//   [u8;32]  fee_policy_id                         = 32 @ 288
//   [u8;32]  insurance_policy_id                   = 32 @ 320
//   u64      status_flags                          =  8 @ 352  (352%8=0 Y)
//   [u64;2]  required_issued_token_module_mask     = 16 @ 360
//   [u64;2]  required_collateral_module_mask       = 16 @ 376
//   [u64;2]  forbidden_issued_token_extension_mask = 16 @ 392
//   [u64;2]  forbidden_collateral_extension_mask   = 16 @ 408
//   [u8;32]  asset_mint_limit_policy_id            = 32 @ 424
//   [u8;32]  asset_redeem_limit_policy_id          = 32 @ 456
//   [u8;32]  counterparty_limit_policy_id          = 32 @ 488
//   [u8;32]  executor_limit_policy_id              = 32 @ 520
//   [u8;64]  _reserved                             = 64 @ 552
//                                                   ─────
//                                                   616 bytes
pub const PATHWAY_POLICY_RESERVED_SIZE: usize = 64;
pub const PATHWAY_POLICY_SIZE: usize          = 616;

// ─── State ────────────────────────────────────────────────────────────────────

/// Defines the rules governing a single settlement pathway.
/// Seed: [b"pathway-policy", pathway_id]
///
/// pathway_id is a 32-byte opaque identifier generated by the operator
/// and referenced in settlement intents, evidence events, and Annex X.
#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable)]
pub struct PathwayPolicy {
    pub discriminator:                         [u8; 8],
    pub version:                               u16,
    pub bump:                                  u8,

    /// One of `pathway_kind::*` constants.
    pub pathway_kind:                          u8,
    pub _pad0:                                 [u8; 4],

    /// Opaque pathway identifier - must match Annex X entry.
    pub pathway_id:                            [u8; 32],

    /// Collateral asset mint this pathway operates on.
    pub asset_mint:                            Pubkey,

    /// Issued token mint this pathway produces or burns.
    pub issued_token_mint:                     Pubkey,

    /// Allowed CPI program-ID bitmask. Reserved; not enforced (issue #44).
    pub allowed_program_mask:                  [u64; 2],

    /// Allowed instruction-discriminant bitmask. Reserved; not enforced (issue #44).
    pub allowed_instruction_mask:              [u64; 2],

    /// Exact executor identity selected for this pathway. The executor must
    /// still hold the pathway-scoped execution role and sign the settlement.
    /// `Pubkey::default()` means any role-permitted executor may execute.
    pub designated_executor:                   Pubkey,

    /// Source-token-account constraint bitfield. Reserved; not enforced (issue #44).
    pub source_account_policy:                 u64,

    /// Destination-token-account constraint bitfield. Reserved; not enforced (issue #44).
    pub destination_account_policy:            u64,

    /// Compartment policy ID binding reserve routing for this pathway.
    /// Zero if compartment module is inactive.
    pub reserve_compartment_policy_id:         [u8; 32],

    /// Limit policy that gates this pathway. Zero = no limit policy.
    pub limit_policy_id:                       [u8; 32],

    /// Evidence policy binding required emitted fields. Zero = no policy.
    pub evidence_policy_id:                    [u8; 32],

    /// Fee policy applied on settlement through this pathway. Zero = no fees.
    pub fee_policy_id:                         [u8; 32],

    /// Insurance policy reference. Zero = no insurance reference.
    pub insurance_policy_id:                   [u8; 32],

    /// Pathway-level status flags. Uses `status_flag::*` bits.
    pub status_flags:                          u64,

    /// Required issued-token module bitmask. Reserved; not enforced (issue #44).
    pub required_issued_token_module_mask:     [u64; 2],

    /// Required collateral module bitmask. Reserved; not enforced (issue #44).
    pub required_collateral_module_mask:       [u64; 2],

    /// Forbidden issued-token extension bitmask. Reserved; not enforced (issue #44).
    pub forbidden_issued_token_extension_mask: [u64; 2],

    /// Bitmask of collateral extensions that must NOT be present on the asset.
    pub forbidden_collateral_extension_mask:   [u64; 2],

    /// ASSET-scoped limit policy capping daily gross collateral deposited
    /// through this pathway's asset (spec §5.8 "per asset daily gross mint
    /// max"). scope_key must equal `asset_mint`. Zero = dimension disabled.
    pub asset_mint_limit_policy_id:            [u8; 32],

    /// ASSET-scoped limit policy capping daily gross asset released on redeem
    /// (spec §5.8 "per asset daily gross redeem max"). scope_key must equal
    /// `asset_mint`. Zero = dimension disabled.
    pub asset_redeem_limit_policy_id:          [u8; 32],

    /// COUNTERPARTY-scoped template limit policy (scope_key = default).
    /// Usage windows accrue per concrete counterparty key. Mandatory for
    /// DELEGATED pathways; optional for TRILATERAL pathways; disabled for
    /// pathway kinds whose handlers do not expose this dimension.
    pub counterparty_limit_policy_id:          [u8; 32],

    /// EXECUTOR-scoped template limit policy (scope_key = default). Only
    /// meaningful on delegated / trilateral pathways. Zero = disabled.
    pub executor_limit_policy_id:              [u8; 32],

    /// Append-only layout headroom. Must remain zero until consumed by a
    /// versioned layout change, and must be replenished in that same change.
    pub _reserved:                             [u8; 64],
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
impl PathwayPolicy {
    /// Canonical semantic account bytes. Reserved layout headroom is excluded
    /// from value-hash preimages so future tail use cannot silently change pins.
    #[inline]
    pub(crate) fn semantic_bytes(&self) -> &[u8] {
        &bytemuck::bytes_of(self)[..PATHWAY_POLICY_SIZE - PATHWAY_POLICY_RESERVED_SIZE]
    }

    /// Canonical config-change payload. `PATHWAY_PAUSE` is an operational
    /// containment bit managed by `set_pathway_pause`, not a pathway-policy
    /// term. Normalizing only that bit prevents emergency pause/unpause actions
    /// from invalidating unrelated in-flight governance proposals.
    pub(crate) fn config_change_payload(
        &self,
    ) -> [u8; PATHWAY_POLICY_SIZE - PATHWAY_POLICY_RESERVED_SIZE] {
        let mut normalized = *self;
        normalized.status_flags &= !status_flag::PATHWAY_PAUSE;
        normalized.zero_reserved();

        let mut payload = [0u8; PATHWAY_POLICY_SIZE - PATHWAY_POLICY_RESERVED_SIZE];
        payload.copy_from_slice(normalized.semantic_bytes());
        payload
    }

    #[inline]
    pub(crate) fn zero_reserved(&mut self) {
        self._reserved = [0u8; PATHWAY_POLICY_RESERVED_SIZE];
    }

    pub fn pda(pathway_id: &[u8; 32], program_id: &Pubkey) -> (Pubkey, u8) {
        Pubkey::find_program_address(
            &[seeds::PATHWAY_POLICY, pathway_id.as_ref()],
            program_id,
        )
    }

    pub fn verify_pda(
        account:    &AccountInfo,
        pathway_id: &[u8; 32],
        program_id: &Pubkey,
    ) -> Result<u8, ProgramError> {
        let (expected, bump) = Self::pda(pathway_id, program_id);

        if account.key != &expected {
            return Err(ChanceryError::InvalidPda.into());
        }

        Ok(bump)
    }

    pub fn load<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::Ref<'a, Self>, ProgramError> {
        let state = crate::state_loader::load_state::<Self>(
            account,
            PATHWAY_POLICY_SIZE,
            PATHWAY_POLICY_DISCRIMINATOR,
            ChanceryError::NotInitialized,
        )?;

        Ok(state)
    }

    pub(crate) fn load_for_verified_pda<'a>(
        account: &'a AccountInfo<'a>,
        pathway_id: &[u8; 32],
        expected_bump: u8,
    ) -> Result<core::cell::Ref<'a, Self>, ProgramError> {
        let state = Self::load(account)?;

        if state.pathway_id != *pathway_id {
            return Err(ChanceryError::InvalidPda.into());
        }

        crate::state_loader::assert_stored_bump_matches(state.bump, expected_bump)?;

        Ok(state)
    }

    /// Load initialized state and prove that its identity fields resolve to
    /// this account's canonical PDA and stored bump.
    pub fn load_verified<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::Ref<'a, Self>, ProgramError> {
        let state = Self::load(account)?;
        let expected_bump = Self::verify_pda(account, &state.pathway_id, &crate::id())?;

        if state.bump != expected_bump {
            return Err(ChanceryError::StoredBumpMismatch.into());
        }

        Ok(state)
    }

    pub fn load_mut<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::RefMut<'a, Self>, ProgramError> {
        let state = crate::state_loader::load_state_mut::<Self>(
            account,
            PATHWAY_POLICY_SIZE,
            PATHWAY_POLICY_DISCRIMINATOR,
            ChanceryError::NotInitialized,
        )?;

        Ok(state)
    }

    pub(crate) fn load_mut_for_verified_pda<'a>(
        account: &'a AccountInfo<'a>,
        pathway_id: &[u8; 32],
        expected_bump: u8,
    ) -> Result<core::cell::RefMut<'a, Self>, ProgramError> {
        let state = Self::load_mut(account)?;

        if state.pathway_id != *pathway_id {
            return Err(ChanceryError::InvalidPda.into());
        }

        crate::state_loader::assert_stored_bump_matches(state.bump, expected_bump)?;

        Ok(state)
    }

    /// Mutable counterpart to `load_verified`.
    pub fn load_verified_mut<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::RefMut<'a, Self>, ProgramError> {
        let state = Self::load_mut(account)?;
        let expected_bump = Self::verify_pda(account, &state.pathway_id, &crate::id())?;

        if state.bump != expected_bump {
            return Err(ChanceryError::StoredBumpMismatch.into());
        }

        Ok(state)
    }

    pub fn load_uninitialized_mut<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::RefMut<'a, Self>, ProgramError> {
        crate::state_loader::load_uninitialized_state_mut::<Self>(
            account,
            PATHWAY_POLICY_SIZE,
            ChanceryError::AlreadyInitialized,
        )
    }

    // ── Guards ────────────────────────────────────────────────────────────────

    pub fn assert_active(&self) -> Result<(), ProgramError> {
        if self.status_flags & status_flag::PATHWAY_PAUSE != 0 {
            return Err(ChanceryError::PathwayPaused.into());
        }

        if self.status_flags & status_flag::INITIALIZED == 0 {
            return Err(ChanceryError::PathwayPolicyNotFound.into());
        }

        Ok(())
    }

    pub fn assert_kind(&self, expected: u8) -> Result<(), ProgramError> {
        if self.pathway_kind != expected {
            return Err(ChanceryError::PathwayKindMismatch.into());
        }

        Ok(())
    }

    /// Assert the given executor is permitted by this pathway. A configured
    /// `designated_executor` is an exact-match constraint; the default key
    /// leaves selection open to any executor holding the required role.
    pub fn assert_executor(&self, executor: &Pubkey) -> Result<(), ProgramError> {
        if self.designated_executor != Pubkey::default()
            && executor != &self.designated_executor
        {
            return Err(ChanceryError::ExecutorNotPermitted.into());
        }

        Ok(())
    }

    /// Returns true if this pathway has an active fee policy reference.
    #[inline]
    pub fn has_fee_policy(&self) -> bool {
        self.fee_policy_id != [0u8; 32]
    }

    /// Returns true if this pathway has an active limit policy reference.
    #[inline]
    pub fn has_limit_policy(&self) -> bool {
        self.limit_policy_id != [0u8; 32]
    }

    /// Returns true if this pathway enforces the per-asset daily gross mint cap.
    #[inline]
    pub fn has_asset_mint_limit_policy(&self) -> bool {
        self.asset_mint_limit_policy_id != [0u8; 32]
    }

    /// Returns true if this pathway enforces the per-asset daily gross redeem cap.
    #[inline]
    pub fn has_asset_redeem_limit_policy(&self) -> bool {
        self.asset_redeem_limit_policy_id != [0u8; 32]
    }

    /// Returns true if this pathway enforces per-counterparty daily caps.
    #[inline]
    pub fn has_counterparty_limit_policy(&self) -> bool {
        self.counterparty_limit_policy_id != [0u8; 32]
    }

    /// Returns true if this pathway enforces per-executor daily caps.
    #[inline]
    pub fn has_executor_limit_policy(&self) -> bool {
        self.executor_limit_policy_id != [0u8; 32]
    }

    /// Returns true if this pathway has an active evidence policy reference.
    #[inline]
    pub fn has_evidence_policy(&self) -> bool {
        self.evidence_policy_id != [0u8; 32]
    }

    fn assert_identity_and_kind_sanity(&self) -> Result<(), ProgramError> {
        if !matches!(
            self.pathway_kind,
            pathway_kind::DIRECT
                | pathway_kind::DELEGATED
                | pathway_kind::TRILATERAL
                | pathway_kind::CROSS_CHAIN_MINT
                | pathway_kind::CROSS_CHAIN_REDEEM
        ) {
            return Err(ChanceryError::PathwayKindMismatch.into());
        }

        if self.pathway_id == [0u8; 32]
            || self.asset_mint == Pubkey::default()
            || self.issued_token_mint == Pubkey::default()
        {
            return Err(ChanceryError::PathwayDependencyMissing.into());
        }

        if self.asset_mint == self.issued_token_mint {
            return Err(ChanceryError::IssuedTokenCannotBeCollateral.into());
        }

        let program_id = crate::id();
        assert_optional_external_identity(&self.designated_executor, &program_id)?;

        // Direct and cross-chain handlers have no pathway executor account;
        // persisting one would advertise a restriction they cannot enforce.
        if matches!(
            self.pathway_kind,
            pathway_kind::DIRECT
                | pathway_kind::CROSS_CHAIN_MINT
                | pathway_kind::CROSS_CHAIN_REDEEM
        ) && self.designated_executor != Pubkey::default()
        {
            return Err(ChanceryError::ExecutorNotPermitted.into());
        }


        Ok(())
    }

    /// Reject state that advertises controls unavailable in the active MVP.
    /// Later modules and reserved masks must remain zero until their handlers
    /// are enabled and settlement enforces them.
    pub fn assert_runtime_supported(&self) -> Result<(), ProgramError> {
        self.assert_identity_and_kind_sanity()?;
        if self.allowed_program_mask != [0u64; 2]
            || self.allowed_instruction_mask != [0u64; 2]
            || self.source_account_policy != 0
            || self.destination_account_policy != 0
            || self.required_issued_token_module_mask != [0u64; 2]
            || self.required_collateral_module_mask != [0u64; 2]
        {
            return Err(ChanceryError::PathwayDependencyMissing.into());
        }

        if self.reserve_compartment_policy_id != [0u8; 32]
            || self.insurance_policy_id != [0u8; 32]
        {
            return Err(ChanceryError::ModuleNotEnabled.into());
        }

        // Direct settlement has no executor account and therefore cannot honor
        // an executor-scoped policy. Cross-chain handlers currently enforce the
        // pathway policy only, so dimension references are rejected there until
        // the corresponding accounts and checks are added to those instructions.
        if self.pathway_kind == pathway_kind::DIRECT
            && self.has_executor_limit_policy()
        {
            return Err(ChanceryError::PathwayDependencyMissing.into());
        }

        // A delegated executor can consume a principal's signed allowance
        // without the principal co-signing each settlement. Bind every
        // delegated pathway to a counterparty-scoped daily containment policy.
        if self.pathway_kind == pathway_kind::DELEGATED
            && !self.has_counterparty_limit_policy()
        {
            return Err(ChanceryError::PathwayDependencyMissing.into());
        }

        if matches!(
            self.pathway_kind,
            pathway_kind::CROSS_CHAIN_MINT | pathway_kind::CROSS_CHAIN_REDEEM
        ) && (self.has_asset_mint_limit_policy()
            || self.has_asset_redeem_limit_policy()
            || self.has_counterparty_limit_policy()
            || self.has_executor_limit_policy()
            || self.has_evidence_policy()
            || self.forbidden_collateral_extension_mask != [0u64; 2])
        {
            return Err(ChanceryError::PathwayDependencyMissing.into());
        }

        Ok(())
    }

    /// Validate that observed collateral extensions are not forbidden by this pathway.
    pub fn assert_collateral_extensions_allowed(
        &self,
        observed: [u64; 2],
    ) -> Result<(), ProgramError> {
        let forbidden = self.forbidden_collateral_extension_mask;

        if (observed[0] & forbidden[0] != 0) || (observed[1] & forbidden[1] != 0) {
            return Err(ChanceryError::ForbiddenExtension.into());
        }

        Ok(())
    }

    /// Validate that observed issued-token extensions are not forbidden by this pathway.
    pub fn assert_issued_token_extensions_allowed(
        &self,
        observed: [u64; 2],
    ) -> Result<(), ProgramError> {
        let forbidden = self.forbidden_issued_token_extension_mask;

        if (observed[0] & forbidden[0] != 0) || (observed[1] & forbidden[1] != 0) {
            return Err(ChanceryError::ForbiddenExtension.into());
        }

        Ok(())
    }
}

// ─── Size assertion ───────────────────────────────────────────────────────────
const _: () = assert!(
    core::mem::size_of::<PathwayPolicy>() == PATHWAY_POLICY_SIZE,
    "PathwayPolicy size mismatch - update PATHWAY_POLICY_SIZE",
);

#[cfg(test)]
mod tests {
    use super::*;

    fn executable_policy(kind: u8) -> PathwayPolicy {
        let mut policy = PathwayPolicy::zeroed();
        policy.pathway_kind = kind;
        policy.pathway_id = [1u8; 32];
        policy.asset_mint = Pubkey::new_unique();
        policy.issued_token_mint = Pubkey::new_unique();
        policy
    }

    #[test]
    fn unknown_pathway_kinds_fail_closed() {
        for kind in [5u8, 0x7f, 0xff] {
            let policy = executable_policy(kind);
            assert_eq!(
                policy.assert_runtime_supported(),
                Err(ChanceryError::PathwayKindMismatch.into()),
            );
        }
    }

    #[test]
    fn designated_executor_is_rejected_when_no_handler_can_enforce_it() {
        for kind in [
            pathway_kind::DIRECT,
            pathway_kind::CROSS_CHAIN_MINT,
            pathway_kind::CROSS_CHAIN_REDEEM,
        ] {
            let mut policy = executable_policy(kind);
            policy.designated_executor = Pubkey::new_unique();
            assert_eq!(
                policy.assert_runtime_supported(),
                Err(ChanceryError::ExecutorNotPermitted.into()),
            );
        }
    }

    #[test]
    fn cross_chain_pathways_reject_unenforced_evidence_policy_references() {
        for kind in [pathway_kind::CROSS_CHAIN_MINT, pathway_kind::CROSS_CHAIN_REDEEM] {
            let mut policy = executable_policy(kind);
            policy.evidence_policy_id = [9u8; 32];

            assert_eq!(
                policy.assert_runtime_supported(),
                Err(ChanceryError::PathwayDependencyMissing.into()),
            );
        }
    }

    #[test]
    fn protocol_signer_pdas_cannot_be_pathway_executors() {
        let seeds = [
            crate::constants::seeds::MINT_AUTHORITY,
            crate::constants::seeds::FREEZE_AUTHORITY,
            crate::constants::seeds::RESERVE_AUTHORITY,
            crate::constants::seeds::CLOSE_MINT_AUTHORITY,
            crate::constants::seeds::TRANSFER_HOOK_AUTHORITY,
            crate::constants::seeds::PERMANENT_DELEGATE_AUTHORITY,
            crate::constants::seeds::METADATA_POINTER_AUTHORITY,
            crate::constants::seeds::METADATA_UPDATE_AUTHORITY,
            crate::constants::seeds::PAUSE_AUTHORITY,
            crate::constants::seeds::CONFIDENTIAL_TRANSFER_AUTHORITY,
            crate::constants::seeds::DEFAULT_ACCOUNT_STATE_AUTHORITY,
            crate::constants::seeds::EVENT_AUTHORITY,
        ];
        let program_id = crate::id();
        for seed in seeds {
            let mut policy = executable_policy(pathway_kind::DELEGATED);
            policy.designated_executor = Pubkey::find_program_address(&[seed], &program_id).0;
            assert_eq!(
                policy.assert_runtime_supported(),
                Err(ChanceryError::ProtocolSignerIdentityForbidden.into()),
            );
        }
    }

    #[test]
    fn self_collateral_is_rejected_without_conflating_policy_id_namespaces() {
        let mut self_collateral = executable_policy(pathway_kind::DIRECT);
        self_collateral.asset_mint = self_collateral.issued_token_mint;
        assert_eq!(
            self_collateral.assert_runtime_supported(),
            Err(ChanceryError::IssuedTokenCannotBeCollateral.into()),
        );

        let mut shared_identifier = executable_policy(pathway_kind::DELEGATED);
        shared_identifier.limit_policy_id = [9u8; 32];
        shared_identifier.counterparty_limit_policy_id = [9u8; 32];
        assert!(shared_identifier.assert_runtime_supported().is_ok());
    }
}
