use bytemuck::{Pod, Zeroable};
use solana_account_info::AccountInfo;
use solana_program_error::ProgramError;
use solana_pubkey::Pubkey;

use crate::{
    constants::{compartment_kind, seeds, status_flag},
    error::ChanceryError,
};

// ─── Discriminator ────────────────────────────────────────────────────────────
pub const RESERVE_COMPARTMENT_DISCRIMINATOR: [u8; 8] =
    [0x72, 0x73, 0x76, 0x63, 0x6d, 0x70, 0x74, 0x00];

// ─── Compartment policy flag bits ─────────────────────────────────────────────
/// Bits for `policy_flags`.
pub mod compartment_policy_flag {
    /// Compartment may receive intake from settlement flows.
    pub const INTAKE_PERMITTED:     u64 = 1 << 0;
    /// Balances in this compartment may be promoted to ClearedOperating.
    pub const PROMOTION_PERMITTED:  u64 = 1 << 1;
    /// Compartment may feed into approved downstream destinations.
    pub const DOWNSTREAM_PERMITTED: u64 = 1 << 2;
    /// Require a ProvenanceCase approval before promotion.
    pub const REQUIRE_PROVENANCE:   u64 = 1 << 3;
}

// ─── Account size ─────────────────────────────────────────────────────────────
//   [u8;8]   discriminator      =  8 @ 0
//   u16      version            =  2 @ 8
//   u8       bump               =  1 @ 10
//   u8       compartment_kind   =  1 @ 11
//   [u8;4]   _pad0              =  4 @ 12  -> [u8;32] at 16
//   [u8;32]  compartment_id     = 32 @ 16
//   [u8;32]  asset_mint         = 32 @ 48
//   [u8;32]  asset_token_program = 32 @ 80
//   [u8;32]  reserve_compartment_token_account = 32 @ 112
//   u64      policy_flags       =  8 @ 144  (144%8=0 Y)
//   u64      status_flags       =  8 @ 152
//   [u8;32]  created_by         = 32 @ 160
//   [u8;32]  _reserved          = 32 @ 192
//                                ─────
//                                224 bytes
pub const RESERVE_COMPARTMENT_SIZE: usize = 224;

// ─── State ────────────────────────────────────────────────────────────────────

/// Operator-owned internal reserve control lane.
/// Seed: [b"reserve-compartment", asset_mint, compartment_id]
///
/// Characterization (spec 06 §6.2):
///   - Not a customer subaccount.
///   - Not escrow, FBO, or trust.
///   - Not a beneficial ownership tracker.
///   - Purely an Operator-side internal risk and sanitation control.
///
/// The actual token balance lives in `reserve_compartment_token_account` (a standard token
/// account whose owner is a program PDA). This struct is the policy
/// and routing record only.
#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable)]
pub struct ReserveCompartment {
    pub discriminator:                     [u8; 8],
    pub version:                           u16,
    pub bump:                              u8,
    
    /// One of `compartment_kind::*` constants.
    pub compartment_kind:                  u8,
    pub _pad0:                             [u8; 4],

    /// Opaque compartment ID - generated by the operator.
    pub compartment_id:                    [u8; 32],
    
    /// The collateral asset mint this compartment holds.
    pub asset_mint:                        Pubkey,
    
    /// Token program owning `reserve_compartment_token_account`.
    pub asset_token_program:               Pubkey,
    
    /// The actual token account holding the reserve compartment balance.
    pub reserve_compartment_token_account: Pubkey,

    /// Bitfield using `compartment_policy_flag::*` constants.
    pub policy_flags:                      u64,
    
    /// Bitfield using `status_flag::*` constants.
    /// `COMPARTMENT_FROZEN` bit blocks all inflow and outflow.
    pub status_flags:                      u64,

    /// The authority that created this compartment.
    pub created_by:                        Pubkey,

    pub _reserved:                         [u8; 32],
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
impl ReserveCompartment {
    pub fn pda(
        asset_mint:     &Pubkey,
        compartment_id: &[u8; 32],
        program_id:     &Pubkey,
    ) -> (Pubkey, u8) {
        Pubkey::find_program_address(
            &[
                seeds::RESERVE_COMPARTMENT,
                asset_mint.as_ref(),
                compartment_id.as_ref(),
            ],
            program_id,
        )
    }

    pub fn verify_pda(
        account:        &AccountInfo,
        asset_mint:     &Pubkey,
        compartment_id: &[u8; 32],
        program_id:     &Pubkey,
    ) -> Result<u8, ProgramError> {
        let (expected, bump) = Self::pda(asset_mint, compartment_id, program_id);

        if account.key != &expected {
            return Err(ChanceryError::InvalidPda.into());
        }

        Ok(bump)
    }

    pub fn load<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::Ref<'a, Self>, ProgramError> {
        let state = crate::state_loader::load_state::<Self>(
            account,
            RESERVE_COMPARTMENT_SIZE,
            RESERVE_COMPARTMENT_DISCRIMINATOR,
            ChanceryError::NotInitialized,
        )?;

        Ok(state)
    }

    /// Load initialized state and prove that its identity fields resolve to
    /// this account's canonical PDA and stored bump.
    pub fn load_verified<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::Ref<'a, Self>, ProgramError> {
        let state = Self::load(account)?;
        let expected_bump = Self::verify_pda(account, &state.asset_mint, &state.compartment_id, &crate::id())?;

        if state.bump != expected_bump {
            return Err(ChanceryError::StoredBumpMismatch.into());
        }

        Ok(state)
    }

    pub fn load_mut<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::RefMut<'a, Self>, ProgramError> {
        let state = crate::state_loader::load_state_mut::<Self>(
            account,
            RESERVE_COMPARTMENT_SIZE,
            RESERVE_COMPARTMENT_DISCRIMINATOR,
            ChanceryError::NotInitialized,
        )?;

        Ok(state)
    }

    /// Mutable counterpart to `load_verified`.
    pub fn load_verified_mut<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::RefMut<'a, Self>, ProgramError> {
        let state = Self::load_mut(account)?;
        let expected_bump = Self::verify_pda(account, &state.asset_mint, &state.compartment_id, &crate::id())?;

        if state.bump != expected_bump {
            return Err(ChanceryError::StoredBumpMismatch.into());
        }

        Ok(state)
    }

    pub fn load_uninitialized_mut<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::RefMut<'a, Self>, ProgramError> {
        crate::state_loader::load_uninitialized_state_mut::<Self>(
            account,
            RESERVE_COMPARTMENT_SIZE,
            ChanceryError::AlreadyInitialized,
        )
    }

    // ── Guards ────────────────────────────────────────────────────────────────

    pub fn assert_not_frozen(&self) -> Result<(), ProgramError> {
        if self.status_flags & status_flag::COMPARTMENT_FROZEN != 0 {
            return Err(ChanceryError::CompartmentFrozen.into());
        }

        Ok(())
    }

    pub fn assert_intake_permitted(&self) -> Result<(), ProgramError> {
        self.assert_not_frozen()?;
        
        if self.policy_flags & compartment_policy_flag::INTAKE_PERMITTED == 0 {
            return Err(ChanceryError::CompartmentKindForbidsPromotion.into());
        }

        Ok(())
    }

    pub fn assert_promotion_permitted(&self) -> Result<(), ProgramError> {
        self.assert_not_frozen()?;

        if self.policy_flags & compartment_policy_flag::PROMOTION_PERMITTED == 0 {
            return Err(ChanceryError::CompartmentKindForbidsPromotion.into());
        }

        Ok(())
    }

    pub fn assert_is_cleared_operating(&self) -> Result<(), ProgramError> {
        if self.compartment_kind != compartment_kind::CLEARED_OPERATING {
            return Err(ChanceryError::CompartmentKindForbidsPromotion.into());
        }

        Ok(())
    }
}

// ─── Size assertion ───────────────────────────────────────────────────────────
const _: () = assert!(
    core::mem::size_of::<ReserveCompartment>() == RESERVE_COMPARTMENT_SIZE,
    "ReserveCompartment size mismatch - update RESERVE_COMPARTMENT_SIZE",
);
