[package]
name                       = "chancery-devnet-faucet"
edition                    = "2024"
version                    = "0.1.0"
publish                    = false

[lib]
crate-type                 = ["cdylib", "lib"]

[dependencies]
borsh                      = { workspace = true }
solana-clock               = { workspace = true }
solana-sysvar              = { workspace = true }
chancery                   = { path = "../chancery", features = ["no-entrypoint"] }
solana-account-info        = { workspace = true }
solana-cpi                 = { workspace = true }
solana-instruction         = { workspace = true }
solana-msg                 = { workspace = true }
solana-program-entrypoint  = { workspace = true }
solana-program-error       = { workspace = true }
solana-pubkey              = { workspace = true }

[lints.rust]
unexpected_cfgs            = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
