use bytemuck::{Pod, Zeroable};
use solana_account_info::AccountInfo;
use solana_program_error::ProgramError;
use solana_pubkey::Pubkey;

use crate::{
    constants::{case_status, seeds},
    error::ChanceryError,
};

// ─── Discriminator ────────────────────────────────────────────────────────────
pub const ENFORCEMENT_CASE_DISCRIMINATOR: [u8; 8] =
    [0x65, 0x6e, 0x66, 0x63, 0x61, 0x73, 0x65, 0x00];

// ─── Action kind constants ────────────────────────────────────────────────────
/// The action this enforcement case authorises.
pub mod action_kind {
    /// Freeze the subject's token account via Token-2022 freeze authority.
    pub const FREEZE_TOKEN_ACCOUNT: u8 = 0x00;
    /// Thaw a previously frozen token account.
    pub const THAW_TOKEN_ACCOUNT:   u8 = 0x01;
    /// Forced burn of tokens from the subject's account.
    /// Requires the most restrictive authority chain - governance + enforcement.
    pub const FORCED_BURN:          u8 = 0x02;
}

// ─── Account size ─────────────────────────────────────────────────────────────
//   [u8;8]   discriminator           =  8 @ 0
//   u16      version                 =  2 @ 8
//   u8       bump                    =  1 @ 10
//   u8       status                  =  1 @ 11
//   u8       action_kind             =  1 @ 12
//   [u8;3]   _pad0                   =  3 @ 13  -> [u8;32] at 16
//   [u8;32]  case_id                 = 32 @ 16
//   [u8;32]  subject                 = 32 @ 48
//   [u8;32]  asset_mint              = 32 @ 80
//   [u8;32]  related_pathway_id      = 32 @ 112
//   [u8;32]  evidence_hash           = 32 @ 144
//   u32      reason_code             =  4 @ 176
//   [u8;4]   _pad1                   =  4 @ 180  -> Pubkey at 184
//   [u8;32]  opened_by               = 32 @ 184
//   [u8;32]  approved_by             = 32 @ 216
//   [u8;32]  _reserved               = 32 @ 248
//                                     ─────
//                                     280 bytes
pub const ENFORCEMENT_CASE_SIZE: usize = 280;

// ─── State ────────────────────────────────────────────────────────────────────

/// Enforcement case authorising a bounded token-side enforcement action.
/// Seed: [seeds::ENFORCEMENT_CASE, case_id]
///
/// IMPORTANT: enforcement cases use the `PROVENANCE_CASE` seed prefix from
/// constants to avoid a separate seed entry. Alternatively, a dedicated
/// `ENFORCEMENT_CASE` seed may be added to constants if disambiguation
/// is required by the operator. The implementation here uses the case_id
/// itself as sufficient disambiguation.
///
/// Characterization (spec 06 §6.8):
///   - Bounded: operates only on the case-specified subject and asset.
///   - Policy-driven: action only executes after APPROVED status is set.
///   - Auditable: fully logged via evidence events.
///   - Separate from normal settlement - not reachable through settlement flow.
///   - Not broad admin god-mode - cannot arbitrarily affect any account.
///
/// Enforcement actions (spec 06 §6.8, §6.9):
///   - FREEZE_TOKEN_ACCOUNT  - token-side freeze via freeze_authority PDA
///   - THAW_TOKEN_ACCOUNT    - token-side thaw via freeze_authority PDA
///   - FORCED_BURN           - burn under separate governance + enforcement co-approval
#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable)]
pub struct EnforcementCase {
    pub discriminator:       [u8; 8],
    pub version:             u16,
    pub bump:                u8,
    
    /// One of `case_status::*` constants.
    pub status:              u8,
    
    /// One of `action_kind::*` constants.
    pub action_kind:        u8,
    pub _pad0:              [u8; 3],

    /// Opaque case ID generated by the operator.
    pub case_id:            [u8; 32],
    
    /// The wallet or token account subject to enforcement action.
    pub subject:            Pubkey,
    
    /// Collateral or issued asset mint involved.
    pub asset_mint:         Pubkey,
    
    /// The pathway the triggering activity occurred on. Zero if not applicable.
    pub related_pathway_id: [u8; 32],
    
    /// SHA-256 of the off-chain evidence bundle supporting this case.
    pub evidence_hash:      [u8; 32],

    /// Operator-defined reason / regulatory code.
    pub reason_code:        u32,
    pub _pad1:              [u8; 4],

    /// The enforcement_authority that opened the case.
    pub opened_by:          Pubkey,
    
    /// The authority that approved execution. Zero until APPROVED.
    pub approved_by:        Pubkey,

    pub _reserved:          [u8; 32],
}

// ─── Helpers ──────────────────────────────────────────────────────────────────
impl EnforcementCase {
    pub fn pda(case_id: &[u8; 32], program_id: &Pubkey) -> (Pubkey, u8) {
        // Uses a dedicated seed string that must be added to constants::seeds.
        // For now, derivation uses the case_id directly with a fixed prefix.
        // The caller must pass the correctly derived PDA.
        Pubkey::find_program_address(
            &[crate::constants::seeds::ENFORCEMENT_CASE, case_id.as_ref()],
            program_id,
        )
    }

    pub fn verify_pda(
        account:    &AccountInfo,
        case_id:    &[u8; 32],
        program_id: &Pubkey,
    ) -> Result<u8, ProgramError> {
        let (expected, bump) = Self::pda(case_id, program_id);

        if account.key != &expected {
            return Err(ChanceryError::InvalidPda.into());
        }

        Ok(bump)
    }

    pub fn load<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::Ref<'a, Self>, ProgramError> {
        let state = crate::state_loader::load_state::<Self>(
            account,
            ENFORCEMENT_CASE_SIZE,
            ENFORCEMENT_CASE_DISCRIMINATOR,
            ChanceryError::NotInitialized,
        )?;

        Ok(state)
    }

    /// Load initialized state and prove that its identity fields resolve to
    /// this account's canonical PDA and stored bump.
    pub fn load_verified<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::Ref<'a, Self>, ProgramError> {
        let state = Self::load(account)?;
        let expected_bump = Self::verify_pda(account, &state.case_id, &crate::id())?;

        if state.bump != expected_bump {
            return Err(ChanceryError::StoredBumpMismatch.into());
        }

        Ok(state)
    }

    pub fn load_mut<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::RefMut<'a, Self>, ProgramError> {
        let state = crate::state_loader::load_state_mut::<Self>(
            account,
            ENFORCEMENT_CASE_SIZE,
            ENFORCEMENT_CASE_DISCRIMINATOR,
            ChanceryError::NotInitialized,
        )?;

        Ok(state)
    }

    /// Mutable counterpart to `load_verified`.
    pub fn load_verified_mut<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::RefMut<'a, Self>, ProgramError> {
        let state = Self::load_mut(account)?;
        let expected_bump = Self::verify_pda(account, &state.case_id, &crate::id())?;

        if state.bump != expected_bump {
            return Err(ChanceryError::StoredBumpMismatch.into());
        }

        Ok(state)
    }

    pub fn load_uninitialized_mut<'a>(
        account: &'a AccountInfo<'a>,
    ) -> Result<core::cell::RefMut<'a, Self>, ProgramError> {
        crate::state_loader::load_uninitialized_state_mut::<Self>(
            account,
            ENFORCEMENT_CASE_SIZE,
            ChanceryError::AlreadyInitialized,
        )
    }

    // ── Guards ────────────────────────────────────────────────────────────────

    pub fn assert_open(&self) -> Result<(), ProgramError> {
        if self.status != case_status::OPEN {
            return Err(ChanceryError::EnforcementCaseNotApproved.into());
        }

        Ok(())
    }

    /// Assert the case is APPROVED and ready for execution.
    pub fn assert_approved(&self) -> Result<(), ProgramError> {
        if self.status != case_status::APPROVED {
            return Err(ChanceryError::EnforcementCaseNotApproved.into());
        }

        Ok(())
    }

    pub fn assert_action_kind(&self, expected: u8) -> Result<(), ProgramError> {
        if self.action_kind != expected {
            return Err(ChanceryError::UnknownInstruction.into());
        }

        Ok(())
    }
}

// ─── Size assertion ───────────────────────────────────────────────────────────
const _: () = assert!(
    core::mem::size_of::<EnforcementCase>() == ENFORCEMENT_CASE_SIZE,
    "EnforcementCase size mismatch - update ENFORCEMENT_CASE_SIZE",
);
